from ai.config import AIConfig
from ai.router import ModelRouter
from ai.schemas import GenerationRequest, ModelInfo
from ai.service import AIService


class FakeProvider:
    def generate(self, model, prompt, context, config):
        return f"Generated by {model.name}"


def create_service():
    return AIService(
        config=AIConfig(),
        router=ModelRouter(),
        provider=FakeProvider(),
    )


def create_models():
    return [
        ModelInfo(
            name="test-reasoning-model",
            provider="test",
            capabilities=["reasoning"],
            available=True,
        )
    ]


def test_ai_service_generates_normal_response():
    service = create_service()

    request = GenerationRequest(
        prompt="Analyze the evidence.",
        task_type="reasoning",
    )

    response = service.generate(request, create_models())

    assert response.model == "test-reasoning-model"
    assert response.answer == "Generated by test-reasoning-model"
    assert response.verification_status == "requires_review"


def test_ai_response_contains_verification_metadata():
    service = create_service()

    request = GenerationRequest(
        prompt="Analyze the evidence.",
        task_type="reasoning",
    )

    response = service.generate(request, create_models())

    assert response.metadata["generated_analysis"] is True
    assert response.metadata["evidence_verified"] is False
    assert response.metadata["verification_owner"] == "agent"


def test_ai_generation_does_not_make_unsupported_verification_claims():
    service = create_service()

    request = GenerationRequest(
        prompt="Confirm this finding.",
        task_type="reasoning",
    )

    response = service.generate(request, create_models())

    assert response.verification_status == "requires_review"
    assert response.metadata["evidence_verified"] is False