from ai.config import AIConfig
from ai.router import ModelRouter
from ai.schemas import GenerationRequest, ModelInfo
from ai.service import AIService

class FakeProvider:
    def generate(self, model, prompt, context, config):
        return f"Generated by {model.name}"


def test_ai_service_generates_response():
    service = AIService(
        config=AIConfig(),
        router=ModelRouter(),
        provider=FakeProvider(),
    )

    models = [
        ModelInfo(
            name="test-reasoning-model",
            provider="test",
            capabilities=["reasoning"],
            available=True,
        )
    ]

    request = GenerationRequest(
        prompt="Analyze the evidence.",
        task_type="reasoning",
    )

    response = service.generate(request, models)

    assert response.model == "test-reasoning-model"
    assert response.answer == "Generated by test-reasoning-model"
    assert response.verification_status == "requires_review"